name: Continuous Integration and Netlify Deployment

on:
  push:
    branches:
      - main
    paths:
      - "client/**"
  pull_request:
    paths:
      - "client/**"

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: ./client
        run: npm ci

      - name: Run ESLint
        working-directory: ./client
        run: npm run lint

      - name: Build Project
        working-directory: ./client
        run: npm run build

  Deploy-Production:
    runs-on: ubuntu-latest
    needs: CI

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Netlify CLI
        run: npm install --global netlify-cli

      - name: Deploy to Netlify
        run: |
          export NETLIFY_AUTH_TOKEN=${{ secrets.NETLIFY_TOKEN }}
          netlify deploy --dir=./client/dist --prod --site=${{ secrets.NETLIFY_SITE_ID }}
