name: Deploy Server to Vercel

on:
  push:
    paths:
      - "server/**"
      - ".github/workflows/**" # Trigger if workflow files are updated

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Install Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Ensure the version matches your project's requirements

      # Install Vercel CLI globally
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Deploy the server folder to Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          cd server
          vercel --prod --scope your-vercel-team # Replace `your-vercel-team` with your Vercel team if applicable
